Create smart decorator #60
agorlov/lipid pull request #80
Opened 2019-08-29 14:16 UTC by klepatskiy

close #60

2019-08-29 15:47 UTC, agorlov requested changes

2019-08-29 15:47 UTC, agorlov commented on src/Response/RespJson.php
> +final class RespJson implements Response
phpdoc

2019-08-29 15:47 UTC, agorlov commented on src/Response/RespJson.php
> +    public function __construct($json, Response $orig = null)
phpdoc

2019-08-29 15:47 UTC, agorlov commented on src/Response/RespJson.php
> +            ->withHeaders(['Content-type' => 'json'])
application/json

2019-08-30 09:29 UTC, agorlov approved these changes

2019-08-30 09:29 UTC, merged

2019-08-30 09:35 UTC, 0pdd commented
@klepatskiy the puzzle [#82](https://github.com/agorlov/lipid/issues/82) is still not solved.